### ISSUE TITLE
Rollup function is not working  for any transformer type

### ISSUE THREAD

**Issue by mikeengland** [kayak/fireant#12]
Returning data when using the Rollup operation for any transformer type e.g. column_index_table or line_chart results in an error.

Example call:
`print(json.dumps(slicer.manager.line_chart(
        metrics=['clicks'],
        dimensions=['date'],
        dimension_filters=[RangeFilter('date', date.today() - timedelta(days=60), date.today())],
        operations=[Rollup(['date'])]
    )))`

Error message:
`TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

**Comment by twheys** [comment]
Do you get the same error message for all of the transformers?  Can you please post the full stack trace?

**Comment by twheys** [comment]
I was able to reproduce this for the datatables transformer.  Seems that pandas is returning `future.types.newstr.newstr` instead of `str` in some cases.
