### ISSUE TITLE
Using a reference (e.g. YoY) throws a NotImplementedError for interval

### ISSUE THREAD

**Issue by spinningarrow** [kayak/fireant#127]
Using the references feature (http://fireant.readthedocs.io/en/latest/2_slicer.html#comparing-data-to-previous-values) throws a NotImplementedError on the `interval` function. I understand that I need to override the interval function in my subclass of `Database`, but what exactly is the function supposed to do?

**Comment by x8lucas8x** [comment]
@spinningarrow See https://github.com/kayak/fireant/blob/master/fireant/database/vertica.py as an example. This method should return an instantiated pypika's term/function, which could be different from the one implemented above in case you're trying to add support to another database engine (FYI fireant currently supports only vertica). That's necessary for intervals and date truncs cause not all databases comply with strict iso guidelines. We tried to make fireant as engine independent as possible, but those two cases were found to be different in mysql and vertica for instance.

**Comment by twheys** [comment]
Hey @spinningarrow did the answer from @x8lucas8x resolve your issue?

**Comment by spinningarrow** [comment]
@twheys @x8lucas8x thanks for the response! It does help; now I need to figure out how to apply this to SQL Server. Regarding only supporting Vertica, it seems to work fine with SQL Server so far (though I haven't gotten around to overriding `trunc` and `interval` so I guess fireant isn't quite being used to its full potential!)

**Comment by mikeengland** [comment]
@spinningarrow Interesting, thanks for the feedback. If you run into any issues with FireAnt on SQL Server please do let us know or feel free to highlight it in an issue!
