### ISSUE TITLE
Timestamp is not JSON serializable error when rendering a row_index_table

### ISSUE THREAD

**Issue by mikeengland** [kayak/fireant#2]
When running code very similar to the example for rendering a row_index_table and attempting to output this as JSON data, an error is raised:

`...raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Timestamp('2016-06-12 00:00:00') is not JSON serializable`

Code causing the error:
`slicer.manager.row_index_table(
        metrics=['clicks', 'revenue'],
        dimensions=['date', 'device_type'],
        dimension_filters=[RangeFilter('date', date.today() - timedelta(days=60), date.today())]
    )`

Example Python dictionary returned from the above FireAnt statement (Note the Pandas Timestamp data type which cannot be converted to JSON):

`{'Clicks': 123,
   'DT_RowId': 'row_171',
   'Date': Timestamp('2016-08-02 00:00:00'),
   'Device Type': 'Tablet',
   'Revenue': 123},
  {'Clicks': 123,
   'DT_RowId': 'row_172',
   'Date': Timestamp('2016-08-03 00:00:00'),
   'Device Type': 'Tablet',
   'Revenue': 123},`

**Comment by twheys** [comment]
Fixed in 0.0.10
