### ISSUE TITLE
Column Indexed table contains the wrong number of columns

### ISSUE THREAD

**Issue by mikeengland** [kayak/fireant#3]
As per the example at http://fireant.readthedocs.io/en/latest/2_slicer.html, running the following code is returning three columns instead of the expected seven.

> A column-indexed table will contain only one index column and display a metrics column for each combination of subsequent dimensions. For example with the same parameters as above, the result will include seven columns: Day, Clicks (Desktop), Clicks (Tablet), Clicks (Mobile) and Conversions (Desktop), Conversions (Tablet), and Conversions (Mobile).

`slicer.manager.column_index_table(
    metrics=['clicks', 'conversions'],
    dimensions=['date', 'device_type']
)`

This is however returning three columns: Day, Clicks (clicks) and Conversions (conversions).

**Comment by twheys** [comment]
Can you please check if this is still an issue in 0.0.10?

**Comment by mikeengland** [comment]
The values are now returning correctly. Thanks!
