### ISSUE TITLE
The documentation has some issues

### ISSUE THREAD

**Issue by x8lucas8x** [kayak/fireant#74]
The topic "FireAnt - Analytics and Reporting" appears 3 times in the documentation index (i.e. https://fireant.readthedocs.io/en/latest/index.html). Also, the Slicer page (i.e. https://fireant.readthedocs.io/en/latest/2_slicer.html) have some content that is shown 3 times as well. Finally, the latter page has "start-after: _appendix_start: :end-before: _appendix_end:" displayed, which is reStructuredText syntax that is probably not being parsed correctly.

**Comment by mikeengland** [comment]
Fixed in commit 4b7697f
