### ISSUE TITLE
(v0.6.0) Categorical dimensions with no defined labels appear with a label title of None in column indexed tables

### ISSUE THREAD

**Issue by mikeengland** [kayak/fireant#88]
Categorical dimensions are appearing with a label of None in column indexed tables, as if a display label has not been defined by the user, None is being set. This should show the raw db value instead of a prettified user defined value if no user defined value is provided.

**Comment by twheys** [comment]
Is this fixed by your PR?

**Comment by mikeengland** [comment]
Yep this was fixed in the above PR. Closing the issue.
